### ISSUE TITLE
Interview: Becky about Data ACT

### ISSUE THREAD

**Issue by eddietejeda** [18F/performance.gov#4]
Document the key lessons learned from her work on the DATA Act and with spending data and share it with Amin.

Develop question guide for discussion about DATA act.

**Comment by LarryBafundo** [comment]
suggest defining how much of Becky's time we can afford and schedule this for the week of 10/23. similarly, we need to talk to Micah about a replacement for Becky later on in the project, although we'll probably only need (and afford) about a week's worth of that person's time.

**Comment by eddietejeda** [comment]
GOAL: 
our goal is to develop question guide that we provide the agency as a deliverable covering the issues/questions they should anticipate as the project moves along. some of the questions we want to be able to answer are: 

QUESTIONS:
* What are data standard exist in government? 
* What are common problems data-heavy projects encounter? 
* What are the existing data elements and how does the data flow as of today?
*  Is the data, in it's current form, usable? If no, what would make it valuable?

**Comment by eddietejeda** [comment]
Becky began writing her thoughts at:

https://docs.google.com/document/d/1rNT-hj40PFOF6kNJQS2srn0fLH8Kb8OU-eXViqc-zA4/edit#
