### ISSUE TITLE
Identify Groups and Individuals to Interview

### ISSUE THREAD

**Issue by eddietejeda** [18F/performance.gov#41]
Once we define the Agencies we will focus on, we will then need to identify and reach out to the Organizations, Researchers, and Journalists and conduct interviews to understand their needs in more detail.

- [x] Develop email template to send as invitation
- [x] Develop questions for interviews

**Comment by vicuk** [comment]
I don't know what was discussed after I left the meeting, but how is the identification process going to work? I was thinking it was interview based (and it may even start with the four we spoke with during Phase I). If the discovery is just exploring ideas alone, then maybe it doesn't matter. But if the discovery is meant to be co-exploratory where we are working with a few agencies who are willing, we'll only be able to find that out through conversations, interviews, and an invitation.

**Comment by eddietejeda** [comment]
Done. 

https://docs.google.com/spreadsheets/d/1ZFUWQn6N_pnNzovoZ-pYIs1Fsm6gPbJKdsAr08Qz8F8/edit#gid=0
