### ISSUE TITLE
Develop hypotheses to prototype

### ISSUE THREAD

**Issue by hbillings** [18F/performance.gov#47]
Because user research isn't going to start until about halfway through the project, we decided it would be helpful to begin prototyping as a way to test hypotheses and answer questions we still have. We need to figure out what we'd like to test with prototypes prior to building anything.

**Comment by adborden** [comment]
One seed of a hypothesis discussed with @hbillings is that moving the agency performance plan content from PDF to HTML will result in the public being able to find and access performance data more easily.

This is USDA's [annual performance plan and report](https://www.usda.gov/sites/default/files/documents/usda-fy16-annual-performance-report-fy18-performance-plan.pdf).

**Comment by AminPIC** [comment]
I think the content in the quarterly updates going from PDF to HTML would be an even bigger value add since that content changes quarterly.

**Comment by adborden** [comment]
Assigning to @hbillings and I because I think we are both working on this in some capacity.

**Comment by adborden** [comment]
Draft hypotheses https://github.com/18F/performance.gov/blob/master/2.%20Discovery/hypotheses.md
