### ISSUE TITLE
Survey agency performance websites

### ISSUE THREAD

**Issue by adborden** [18F/performance.gov#50]
Agencies are required to publish performance plans on their websites. We can assess these websites the same way we did with other [non-federal performance websites](https://docs.google.com/document/d/1sGln29cghXzJlI7wt8cEXPVnbQ5D9FERz_5whbiahTo/edit#heading=h.li8jmvfql5se). Here are some questions I'm interested in answering:

- How are these agencies using storytelling?
- What formats are agencies publishing this data in (PDF, HTML, machine-readable, etc)?
- Do agencies provide raw data behind the performance data? What format is this data? What system does this data live in?

**Comment by adborden** [comment]
Got this mixed up with another issue, sounds like this is still in progress.

**Comment by hbillings** [comment]
WIP: https://docs.google.com/document/d/1PIdIgtCvqMcTsGdAAg1sosBULQq7YncTL-tbuEZPCKw/edit#
