### ISSUE TITLE
Develop language to reach out to Trade NGO/Academia/Press

### ISSUE THREAD

**Issue by eddietejeda** [18F/performance.gov#52]
We will be reaching out to potential users of site by end of year. We need this language done before the 29th, so we can send by end of year to schedule for new year.

**Comment by onezerojeremy** [comment]
rough draft, available here: https://docs.google.com/document/d/1IfVLZ7prf87HU0zYWAWuwTHyxceySiB5-LT9EwpDqMg/edit#heading=h.iu993b48v6yb

**Comment by onezerojeremy** [comment]
A couple edits later, I think this is a good first version.
