### ISSUE TITLE
Identify interview candidates for the first round of interviews

### ISSUE THREAD

**Issue by adborden** [18F/performance.gov#64]
Identify **think tanks**, **academics**, **NGOs**, and **journalists** who are writing about or working on topics covered by NOAA, Economic Development Administration (EDA), and Census (bureaus of Department of Commerce).

https://docs.google.com/spreadsheets/d/1ZFUWQn6N_pnNzovoZ-pYIs1Fsm6gPbJKdsAr08Qz8F8/edit#gid=0

**Comment by eddietejeda** [comment]
Mostly done, but @adborden is looking for a few more folks to add to interview list.

**Comment by eddietejeda** [comment]
We've done part of this already, but we're thinking about refining the list further. Targeting users that more on the policy side or engaged with the existing framework.
