### ISSUE TITLE
Send client document defining problem statement

### ISSUE THREAD

**Issue by eddietejeda** [18F/performance.gov#8]

**Comment by LarryBafundo** [comment]
I propose that this document consists of the following: 

--a  recap of the activities we conducted & who we spoke with at kickoff 
--a restatement of what a foundation engagement entails and why we do it (modular approach that helps align stakeholders and minimize risk, etc). within this context, explain what are our goals are for the project (i.e., problem definition & to recommend next steps).  
--a summary of what we heard from kickoff (key insights) 
--the problem we're trying to solve (and how this may change over the next few weeks based on what we learn) 
--key hypotheses/questions/learning objectives (however we want to phrase this) that will guide next steps.
--how we'll work (project timeline and key milestones, research approach, team communication plan) 
--next steps/action items (who do we need help scheduling meetings with, when should we start scheduling them?)
