### ISSUE TITLE
Machine-Readability

### ISSUE THREAD

**Issue by OwenAmbur** [18F/performance.gov#92]
Since agencies failed to comply with GPRAMA's February 2018 deadline for publishing their strategic plans in machine-readable format, I did it for them -- temporarily at http://stratml.us/#WorkResults and more permanently at http://stratml.us/history.htm#2018

**Comment by eddietejeda** [comment]
I'll share this with the team. Stay tuned.

**Comment by OwenAmbur** [comment]
Thanks, Eddie.  It would be good if the Performance.gov site were capable of ingesting, indexing, and outputting data in open, standard (ISO 174691), machine-readable StratML format.  It would be great if GSA could also make such capabilities available to State and local agencies as an intergovernmentally shared service.  Please let me know if I can help make that happen.

**Comment by OwenAmbur** [comment]
The key content from the Performance.gov site -- the President's Management Agenda (i.e., the CAP goals and supporting objectives) -- is now available in open, standard, machine-readable StratML Part 1 format at http://stratml.us/drybridge/index.htm#PMA2018

The next step would be to render the performance indicators in StratML Part 2, Performance Plan/Report, format so that they too are machine-readable.

**Comment by AminPIC** [comment]
@OwenAmbur if you create a PR for the StratML to be included into the current Performance.gov website in a logical and user friendly way, then it can be pulled in. Here is the repo: https://github.com/GSA/InterimPerformance-Dot-Gov-2018

**Comment by eddietejeda** [comment]
Closing this since it's now an issue for https://github.com/GSA/InterimPerformance-Dot-Gov-2018
